# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    image: mongo:6.0.3
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks: 
      - mongo_net
    ports:
      - 27017:27017

volumes:
  db-data:
networks:
  mongo_net:
    name: dockerized_mongo
    driver: bridge
